source 'https://rubygems.org'

gem 'aasm'
gem 'attribute_normalizer'
gem 'awesome_print'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'bootstrap3-datetimepicker-rails', '~> 3.1.3'
gem 'breadcrumbs_on_rails'
gem 'cancancan'
gem 'coffee-rails', '~> 4.1.0'
gem 'compass-rails', '~> 2.0.4'
gem 'curb'
gem 'default_value_for'
gem 'devise'
gem 'el_vfs_client'
gem 'enumerize'
gem 'esp-ckeditor'
gem 'esp-commons'
gem 'font-awesome-sass'
gem 'friendly_id'
gem 'gilenson'
gem 'has_scope'
gem 'hashie'
gem 'inherited_resources'
gem 'jquery-rails', '2.1.4'
gem 'jquery-ui-rails'
gem 'kaminari'
gem 'momentjs-rails'
gem 'nested_form'
gem 'non-stupid-digest-assets'
gem 'openteam-commons', '~> 0.3.3'
gem 'paper_trail'
gem 'paperclip'
gem 'paperclip-elvfs'
gem 'paperclip-meta'
gem 'progress_bar', require: false
gem 'protected_attributes'
gem 'rack-utf8_sanitizer'
gem 'rails', '~> 4.2.4'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'rest-client'
gem 'russian'
gem 'sass'
gem 'sass-rails'
gem 'show_for'
gem 'sidekiq'
gem 'simple-navigation'
gem 'simple-rss'
gem 'simple_form'
gem 'sinatra', require: nil
gem 'sitemap_generator'
gem 'spreadsheet'
gem 'sso-auth'
gem 'stop_ie'
gem 'sunspot_rails'
gem 'time_diff'
gem 'truncate_html'
gem 'uglifier'
gem 'user_impersonate2', require: 'user_impersonate'
gem 'uuid'

source 'https://rails-assets.org' do
  gem 'rails-assets-colorbox'
  gem 'rails-assets-jquery', '2.1.4'
  gem 'rails-assets-jquery-file-upload'
  gem 'rails-assets-jquery.inputmask', '~> 3.1.0'
  gem 'rails-assets-modernizr'
  gem 'rails-assets-social-likes'
  gem 'rails-assets-sugar'
  gem 'rails-assets-jquery.scrollTo'
end

group :development do
  gem 'annotate', require: false
  gem 'brakeman', require: false
  gem 'capistrano-db-tasks', '0.4', require: false
  gem 'hirb'
  gem 'letter_opener'
  gem 'openteam-capistrano', '~> 1.0.16'
  gem 'quiet_assets'
  gem 'sqlite3'
  gem 'thin'
end

group :production do
  gem 'pg'
  gem 'unicorn'
end
